In [1]:
import pandas as pd

file_path = "../data/raw/Online_Retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Available sheets:")
print(excel_file.sheet_names)

Available sheets:
['Year 2009-2010', 'Year 2010-2011']

In [2]:
df = pd.read_excel(
    file_path,
    sheet_name="Year 2009-2010"
)

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [5]:
import pandas as pd

file_path = "../data/raw/Online_Retail_II.xlsx"

df_2009_2010 = pd.read_excel(
    file_path,
    sheet_name="Year 2009-2010"
)

df_2010_2011 = pd.read_excel(
    file_path,
    sheet_name="Year 2010-2011"
)

print("Year 2009-2010")
print("Shape:", df_2009_2010.shape)
print("Columns:", df_2009_2010.columns.tolist())

print("\nYear 2010-2011")
print("Shape:", df_2010_2011.shape)
print("Columns:", df_2010_2011.columns.tolist())

Year 2009-2010
Shape: (525461, 8)
Columns: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Year 2010-2011
Shape: (541910, 8)
Columns: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

In [6]:
print("=== Year 2009-2010 ===")
display(df_2009_2010.head())

print("=== Year 2010-2011 ===")
display(df_2010_2011.head())

=== Year 2009-2010 ===

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

=== Year 2010-2011 ===

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
print("=== 2009-2010 Data Types ===")
print(df_2009_2010.dtypes)

print("\n=== 2010-2011 Data Types ===")
print(df_2010_2011.dtypes)

=== 2009-2010 Data Types ===
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

=== 2010-2011 Data Types ===
Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID           float64
Country                   str
dtype: object

In [8]:
print("=== 2009-2010 ===")
print("Shape:", df_2009_2010.shape)

print("\n=== 2010-2011 ===")
print("Shape:", df_2010_2011.shape)

print("\n=== 2009-2010 Summary ===")
display(df_2009_2010.describe(include="all"))

print("\n=== 2010-2011 Summary ===")
display(df_2010_2011.describe(include="all"))

=== 2009-2010 ===
Shape: (525461, 8)

=== 2010-2011 ===
Shape: (541910, 8)

=== 2009-2010 Summary ===

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,525461.0,525461,522533,525461.000000,525461,525461.000000,417534.000000,525461
unique,28816.0,4632,4681,NaN,NaN,NaN,NaN,40
top,537434.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,675.0,3516,3549,NaN,NaN,NaN,NaN,485852
mean,NaN,NaN,NaN,10.337667,2010-06-28 11:37:36.845018,4.688834,15360.645478,NaN
min,NaN,NaN,NaN,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2010-03-21 12:20:00,1.250000,13983.000000,NaN
50%,NaN,NaN,NaN,3.000000,2010-07-06 09:51:00,2.100000,15311.000000,NaN
75%,NaN,NaN,NaN,10.000000,2010-10-15 12:45:00,4.210000,16799.000000,NaN
max,NaN,NaN,NaN,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000,NaN
std,NaN,NaN,NaN,107.424110,NaN,146.126914,1680.811316,NaN

=== 2010-2011 Summary ===

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,541910.0,541910,540456,541910.000000,541910,541910.000000,406830.000000,541910
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552234,2011-07-04 13:35:22.342307,4.611138,15287.684160,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.080957,NaN,96.759765,1713.603074,NaN

In [9]:
print("=== Missing Values: 2009-2010 ===")
print(df_2009_2010.isnull().sum())

print("\n=== Missing Values: 2010-2011 ===")
print(df_2010_2011.isnull().sum())

=== Missing Values: 2009-2010 ===
Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

=== Missing Values: 2010-2011 ===
Invoice             0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
Price               0
Customer ID    135080
Country             0
dtype: int64

In [10]:
print("=== Duplicate Rows ===")
print("2009-2010:", df_2009_2010.duplicated().sum())
print("2010-2011:", df_2010_2011.duplicated().sum())

=== Duplicate Rows ===
2009-2010: 6865
2010-2011: 5268

In [11]:
print("=== Date Range ===")

print(
    "2009-2010:",
    df_2009_2010["InvoiceDate"].min(),
    "to",
    df_2009_2010["InvoiceDate"].max()
)

print(
    "2010-2011:",
    df_2010_2011["InvoiceDate"].min(),
    "to",
    df_2010_2011["InvoiceDate"].max()
)

=== Date Range ===
2009-2010: 2009-12-01 07:45:00 to 2010-12-09 20:01:00
2010-2011: 2010-12-01 08:26:00 to 2011-12-09 12:50:00

In [12]:
print("=== Negative Quantity ===")

print("2009-2010:", (df_2009_2010["Quantity"] < 0).sum())
print("2010-2011:", (df_2010_2011["Quantity"] < 0).sum())

print("\n=== Zero Quantity ===")

print("2009-2010:", (df_2009_2010["Quantity"] == 0).sum())
print("2010-2011:", (df_2010_2011["Quantity"] == 0).sum())

print("\n=== Negative Price ===")

print("2009-2010:", (df_2009_2010["Price"] < 0).sum())
print("2010-2011:", (df_2010_2011["Price"] < 0).sum())

print("\n=== Zero Price ===")

print("2009-2010:", (df_2009_2010["Price"] == 0).sum())
print("2010-2011:", (df_2010_2011["Price"] == 0).sum())

=== Negative Quantity ===
2009-2010: 12326
2010-2011: 10624

=== Zero Quantity ===
2009-2010: 0
2010-2011: 0

=== Negative Price ===
2009-2010: 3
2010-2011: 2

=== Zero Price ===
2009-2010: 3687
2010-2011: 2515

In [13]:
negative_qty_2009 = df_2009_2010[
    df_2009_2010["Quantity"] < 0
]

negative_qty_2010 = df_2010_2011[
    df_2010_2011["Quantity"] < 0
]

print("Sample negative transactions - 2009-2010")
display(negative_qty_2009.head(10))

print("Sample negative transactions - 2010-2011")
display(negative_qty_2010.head(10))

Sample negative transactions - 2009-2010

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
183,C489449,21871,SAVE THE PLANET MUG,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
184,C489449,84946,ANTIQUE SILVER TEA GLASS ETCHED,-12,2009-12-01 10:33:00,1.25,16321.0,Australia
185,C489449,84970S,HANGING HEART ZINC T-LIGHT HOLDER,-24,2009-12-01 10:33:00,0.85,16321.0,Australia
186,C489449,22090,PAPER BUNTING RETRO SPOTS,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

Sample negative transactions - 2010-2011

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
937,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [14]:
print(
    negative_qty_2009["Invoice"].astype(str).str[0].value_counts()
)

print(
    negative_qty_2010["Invoice"].astype(str).str[0].value_counts()
)

Invoice
C    10205
5     1392
4      729
Name: count, dtype: int64
Invoice
C    9288
5    1336
Name: count, dtype: int64